### ISSUE TITLE
How to correct define dictionary 

### ISSUE THREAD

**Issue by lbiaggi** [valentjn/languagetool-languageserver#68]
Hello, I´m trying to make ltex-ls work with the builtin neovim lsp client, the basic stuff is already working (linting) out of the box, but when I try to define a dictionary it doesn't  respect my definition.

**Comment by valentjn** [comment]
Not sure what you did. You have to be more specific. If you set [`ltex.dictionary`](https://valentjn.github.io/vscode-ltex/docs/settings.html#ltexdictionary) on your client, and the client correctly responds to the server's [`workspace/configuration`](https://microsoft.github.io/language-server-protocol/specification#workspace_configuration) requests, then it should work. If it doesn't, open a bug report. If you mean the `Add ... to dictionary` quick fixes, [those have to be implemented by the client](https://github.com/valentjn/ltex-ls/blob/dbc509ea9a7c5dd05ff0b43d12c7dd9b688a70f3/README.md#commands) due to the LSP not yet supporting server-side changes of the configuration (see https://github.com/microsoft/language-server-protocol/issues/874).

**Comment by lbiaggi** [comment]
Ok, my bad
I tested with vscode ltex client and since "pt-BR": [":~/.nvim/spell/dictionary.txt"] worked as expected,

I did something similar to use with ltex-ls, reading txt file is vscode specific?

**Comment by valentjn** [comment]
Ah yes, sorry, that's client-specific. The philosophy of the LSP is that the clients are responsible for configuration and files, the servers only do the actual checking. IMO it wouldn't make much sense to have configuration on both client and server sides. If you want that feature for your client, too, then you'll need to implement [`ltex/workspaceSpecificConfiguration`](https://github.com/valentjn/ltex-ls/blob/dbc509ea9a7c5dd05ff0b43d12c7dd9b688a70f3/README.md#ltexworkspacespecificconfiguration-), where you supply the server with a different `ltex.dictionary` with your external files merged.

The docs need some improvement on which features are client-specific and which aren't.

**Comment by valentjn** [comment]
I updated the docs. Most client-specific sections are now marked with a striped border. This should reduce future confusion.

If LT<sub>E</sub>X is working reasonably well for you, it would be great if you could upload your setup or instructions to a GitHub repo (or somewhere else). People were already asking about LT<sub>E</sub>X for Vim/Neovim (#51). I'd be happy to link your solution in the readme.

**Comment by lbiaggi** [comment]
Hi, thanks @valentjn, sure still a WIP [ltex with neovim-lspconfig](https://gist.github.com/lbiaggi/a3eb761ac2fdbff774b29c88844355b8), but the basics work perfectly! (I can add words to dict file, still missing ignore and false positives, althought, to insert words I created a custom vim function) 

I asked for help neovim/nvim-lspconfig#858 because I am not sure how to implement part of it

**Comment by lbiaggi** [comment]
New version of gist is available (everything is now usable, but you need to define few things, e.g.  language, files), further changes I will send as MR to nvim-lspconfig

BTW, amazing work
